# SPDX-FileCopyrightText: none
# SPDX-License-Identifier: CC0-1.0

include:
  - project: sysadmin/ci-utilities
    file:
      - /gitlab-templates/website-sphinx-app-docs.yml

variables:
    EPUB_NAME: KStarsHandbook 
    WEBSITE_LANGUAGES: bg ca ca@valencia de en es et fr gl it ja ko nl pl pt_BR pt_PT ru sl sv tr uk_UA zh_CN
